### ISSUE TITLE
error when making mofel object from a brain object

### ISSUE THREAD

**Issue by andrewheusser** [ContextLab/supereeg#126]
if fixed that bug, but now I’m getting a new error in line 108 in model.py (when making a model object from a brain object)
`num_corrmat_x, denom_corrmat_x, n_subs = _bo2model(d, self.locs, measure, threshold)`
IndexError: indices are out-of-bounds

**Comment by lucywowen** [comment]
now this issue:
    K[x, y] = np.sum(Z * next_weights)
ValueError: operands could not be broadcast together with shapes (28,28) (40,40)
