### ISSUE TITLE
Warning when converting single Nifti image to Brain objects

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/supereeg#138]
When I convert a single timepoint Nifti image to a Brain object, I get the following runtime warning: `/usr/local/lib/python3.6/site-packages/numpy/lib/function_base.py:4033: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)`

I think this warning should be suppressed.

**Comment by lucywowen** [comment]
this doesn't recreate the error:
`nii = se.Nifti('gray', vox_size=20)`
`bo = se.Brain(nii)`

**Comment by jeremymanning** [comment]
Huh-- so maybe it's not the single timepoint issue.  This produces the error:
`nii = se.Nifti(se.load('gray'))`

**Comment by jeremymanning** [comment]
(By "error" I mean "warning")
